module.exports = require('nconf').argv().env().defaults({
  DOMAIN: 'weareawake.net',
  PORT: 8000,
  COOKIE_SECRET: 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX',
  COOKIE_DOMAIN: '.weareawake.net',

  SESSION_EXPIRATION_MS: 1800000,  // 30 minutes

  FACEBOOK_APP_ID: 447820661996824,
  FACEBOOK_APP_SECRET: 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX',

  TWITTER_API_KEY: 'BO0Z9vowNE9OyeGMQfa5fQ',
  TWITTER_API_SECRET: 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX',

  GOOGLE_RETURN_URL: 'http://weareawake.net/auth/google/callback',
  GOOGLE_REALM: 'http://*.weareawake.net/',

  ROLLBAR_SERVER_TOKEN: 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX',

  CACHE_HOST: '127.0.0.1',
  CACHE_PORT: 6379
});
